### ISSUE TITLE
It's not blocking anything.

### ISSUE THREAD

**Issue by rwb196884** [wolfascu/ChromeHttpRequestBlocker#1]
Added pattern `*doubleclick*` but crap from `ad.doubleclick.net` is still loading.
![not-blocking](https://cloud.githubusercontent.com/assets/12090617/14404768/17c6309a-fe76-11e5-8c38-52630d59f2e4.PNG)

**Comment by wolfascu** [comment]
Thanks for posting this issue! :+1: 

The URL patterns are in fact [Google Extension Match Patterns](https://developer.chrome.com/extensions/match_patterns). In this specific case, the correct pattern to block those requests is `*://*.doubleclick.net/*`.

Honestly, I made this extension for my own use and I was not aware that other people were using it. I am now a bit ashamed about the UI/UX part and I'll think about ways to improve it.

Cheers!

**Comment by rwb196884** [comment]
The UI does give the link to https://developer.chrome.com/extensions/match_patterns
I would have read it but I wanted to simulate a realistic end user ;)

It's a really useful little extension; thanks for making it. What would be fantastic is if it could read the patterns from a text file -- one per line say. (There's a Firefox extension that does exactly this.)

**Comment by wolfascu** [comment]
You're right; I also needed an import/export function once when I needed to transfer my patterns from one Chrome profile to another.
I'll implement this when I have some spare time.
