### ISSUE TITLE
block specific methods

### ISSUE THREAD

**Issue by gera2ld** [wolfascu/ChromeHttpRequestBlocker#3]
Can this extension block specific methods for URLs? Sometimes we may want to block POST requests but allow GET ones.

**Comment by wolfascu** [comment]
At the moment this is not implemented, but it should be possible to add this filter. I'll look into it when I have the time.

**Comment by gera2ld** [comment]
The filter API seems not possible to support this. I have written an extension to support this in another way: <https://chrome.google.com/webstore/detail/request-blocker/cblonkdlnemhdeefhmaoiijjaedcphbf>

**Comment by wolfascu** [comment]
OK, glad you solved it.
